Added method  for search element in collection
iliaKulakov/PhoneHandbook pull request #4
Opened 2018-04-16 20:52 UTC by iliaKulakov

2018-04-17 18:58 UTC, rmuhamedgaliev requested changes
Необходимо править дальше.

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/menu/MainMenu.java
> +                        PhoneHandbookRealisation  PhoneHandbookRealVar = new PhoneHandbookRealisation();
Ты снова нарушаешь соглашение о разработке. Это плохо. Будь внимательнее пожалуйста. В прошлом пулреквесте я уже писал про это. 

> 
> Тут в именовании ошибка. Если ты хочешь писать I в интерфейсах то тогда надо писать в "CamelCase"
> IphoneHandbookRepository -> IPhoneHandbookRepository. А так почитай пожалуйста:
> 
> https://stackoverflow.com/questions/541912/interface-naming-in-java
> https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/menu/MainMenu.java
> +                    ArrayList<Person> personList1 = new ArrayList<Person>();
Для создания тестов може использовать тесты. В будущем мы их рассмотрим. Уже в проекте есть библиотека Junit. 

https://junit.org/junit5/

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/service/PhoneHandbookRealisation.java
> +    ArrayList<Person> personList = new ArrayList<Person>();
Для хранения общего объекта без инициализации можно хранить его в классе SIngletone. Например: https://refactoring.guru/ru/design-patterns/singleton/java/example. Ты сможешь обращаться к нему от куда угодно и будешь уверен, что инициализирован единожды.

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/service/PhoneHandbookRealisation.java
> +            ArrayList<Person> personList = new ArrayList<Person>();
Зачем тут использовать новый экземпляр и заполнять его если ты должен заполнять общую коллекцию. Работай с общим списком как с базой. Тут не надо так делать.

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/menu/MainMenu.java
>                      exit = true;
После окончания ввода, я бы возвращал пользователя в меню, с возможностью выхода, как 4 пункт

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/service/PhoneHandbookRealisation.java
> +    public void toSearchItem2(ArrayList<Person> personList){
Зачем тут использовать новый экземпляр и заполнять его если ты должен заполнять общую коллекцию. Работай с общим списком как с базой. Тут не надо так делать. Бери просто его из синглтона и работай с ним.

2018-04-17 18:58 UTC, rmuhamedgaliev commented on src/main/java/service/PhoneHandbookRealisation.java
> +            Person object = personList.get(i);// не придумал с утра ничего лучше как просто брать обьект из коллекции
Я бы пошел дальше. Как и говорил ранее создал бы 2 коллекции: 
- HashMap<String,Person> - для хранения данных в базе и индексации по имени пользователя
- HashMap<String, List<Person>> - для хранения пользователей по годам

Тут из коробки будет хэширование по ключу.

2018-04-18 04:43 UTC, merged

2018-04-18 20:38 UTC, iliaKulakov commented on src/main/java/service/PhoneHandbookRealisation.java
> +    ArrayList<Person> personList = new ArrayList<Person>();
сделал